POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email" : "user@example.com",
    "password" : "user"
}

##########################################################################
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email" : "user@example.com",
    "password" : "user",
    "birthday": "2000-01-01",
    "name": "user"
}

##########################################################################
GET http://localhost:3000/api/user/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzN2E4NWIyYjNhNGYwZDg1YTE3MjFmOSIsInJvbGUiOiJ1c2VyIiwibmFtZSI6InVzZXIiLCJiaXJ0aGRheSI6IjIwMDAtMDEtMDFUMDA6MDA6MDAuMDAwWiIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJE1pL1FCWHlHNHl2YW1JRTJwWDJiY3U0ZjdETDh5d2ZMY0U3V2xnOVIzTGVDTlBZU2xNMjBPIiwic3RhdGUiOnRydWUsImdsdWNvc2VyYW5nZSI6WzgwLDEyMF19LCJpYXQiOjE2Njg5NzQwODR9.6MRWCIVpQ9Gz2drS87jTuSdrmOJkDho10Pl9YZSyojU


##########################################################################
POST http://localhost:3000/api/user/registerbolus
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzOTRhZjM4MDJhODIzOGM2NjNiOTM1MCIsInJvbGUiOiJ1c2VyIiwibmFtZSI6InVzZXIiLCJiaXJ0aGRheSI6IjIwMDAtMTItMTIiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQ5cWFJRmpzUWpHLjE1TGpVSjF5NUYuVHpWS1M0eUxNMTdNTTlvTnJFSS9kajJiOWlJblpJTyIsInN0YXRlIjp0cnVlLCJnbHVjb3NlcmFuZ2UiOls4MCwxMjBdLCJjYXJiUmF0aW8iOjIwLCJoZWlnaHQiOjIwLCJpZERpYWJldGVzIjoiNjM5NGFhOWZiNmU5ZTZhYWQzNWY0NjgzIiwic2Vuc2l0aXZpdHkiOjIwLCJ3ZWlnaHQiOjIwfSwiaWF0IjoxNjcwNjg4NTc0fQ.CZF88sy6iHT81f5Dt5A_R7tMRluvxyEZ0H32WJHahH8

{
    "amountGlucose": 150,
    "therapy": "terapia",
    "date": "qualquercoisa",
    "time": "lalala",
    "amountHc": 500
}

###
POST http://localhost:3000/api/user/registerbasal
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzOTRhZjM4MDJhODIzOGM2NjNiOTM1MCIsInJvbGUiOiJ1c2VyIiwibmFtZSI6InVzZXIiLCJiaXJ0aGRheSI6IjIwMDAtMTItMTIiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQ5cWFJRmpzUWpHLjE1TGpVSjF5NUYuVHpWS1M0eUxNMTdNTTlvTnJFSS9kajJiOWlJblpJTyIsInN0YXRlIjp0cnVlLCJnbHVjb3NlcmFuZ2UiOls4MCwxMjBdLCJjYXJiUmF0aW8iOjIwLCJoZWlnaHQiOjIwLCJpZERpYWJldGVzIjoiNjM5NGFhOWZiNmU5ZTZhYWQzNWY0NjgzIiwic2Vuc2l0aXZpdHkiOjIwLCJ3ZWlnaHQiOjIwfSwiaWF0IjoxNjcwNjg4NTc0fQ.CZF88sy6iHT81f5Dt5A_R7tMRluvxyEZ0H32WJHahH8

{
    "amountGlucose": 150,
    "therapy": "terapia",
    "date": "qualquercoisa",
    "time": "lalala",
    "amountInsulinTotal": 500

}

###
GET http://localhost:3000/api/admin/getalldiabetes


###
GET http://localhost:3000/api/admin/getallusers
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzODExYjYzZjRmMzljMGM0NzY3ODk4OSIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbiIsImJpcnRoZGF5IjoiMTk5Ny0wMS0xNFQwMDowMDowMC4wMDBaIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDF4R056aXk3RGpmaFFJeVNLaG9uSS53bEdXT2RZZ09oNGljbi5xSm5mQ2ptRTFxNFMxZllDIiwic3RhdGUiOnRydWUsImdsdWNvc2VyYW5nZSI6WzgwLDEyMF19LCJpYXQiOjE2Njk0MDY0MTB9.1oNJg2k3Npiq58xzz_ROCNIuZZUxpl_sWxFawAwkk8w

###
PUT http://localhost:3000/api/user/updateprofile
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzOTRhZjM4MDJhODIzOGM2NjNiOTM1MCIsInJvbGUiOiJ1c2VyIiwibmFtZSI6InVzZXIiLCJiaXJ0aGRheSI6IjIwMDAtMTItMTIiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQ5cWFJRmpzUWpHLjE1TGpVSjF5NUYuVHpWS1M0eUxNMTdNTTlvTnJFSS9kajJiOWlJblpJTyIsInN0YXRlIjp0cnVlLCJnbHVjb3NlcmFuZ2UiOls4MCwxMjBdLCJjYXJiUmF0aW8iOjIwLCJoZWlnaHQiOjIwLCJpZERpYWJldGVzIjoiNjM5NGFhOWZiNmU5ZTZhYWQzNWY0NjgzIiwic2Vuc2l0aXZpdHkiOjIwLCJ3ZWlnaHQiOjIwfSwiaWF0IjoxNjcwNjg4NTc0fQ.CZF88sy6iHT81f5Dt5A_R7tMRluvxyEZ0H32WJHahH8


{
    "height": 175,
    "sensitivity": 20,
    "weight": 65,
    "idDiabetes": "638025f7e9a99b2cd2859b31"
}
