POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email" : "user@example.com",
    "password" : "user"
}

##########################################################################
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email" : "user@example.com",
    "password" : "user",
    "birthday": "2000-01-01",
    "name": "user"
}

##########################################################################
GET http://localhost:3000/api/user/
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzN2E4NWIyYjNhNGYwZDg1YTE3MjFmOSIsInJvbGUiOiJ1c2VyIiwibmFtZSI6InVzZXIiLCJiaXJ0aGRheSI6IjIwMDAtMDEtMDFUMDA6MDA6MDAuMDAwWiIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJE1pL1FCWHlHNHl2YW1JRTJwWDJiY3U0ZjdETDh5d2ZMY0U3V2xnOVIzTGVDTlBZU2xNMjBPIiwic3RhdGUiOnRydWUsImdsdWNvc2VyYW5nZSI6WzgwLDEyMF19LCJpYXQiOjE2Njg5NzQwODR9.6MRWCIVpQ9Gz2drS87jTuSdrmOJkDho10Pl9YZSyojU


##########################################################################
POST http://localhost:3000/user/registerbolus
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzNmUyNmRiOWFiYTEyOTc3NjgyZDNjMyIsInJvbGUiOiJ1c2VyIiwibmFtZSI6Ikp1bGlhbmEgUGF6IiwiYmlydGhkYXkiOiIyMDAyLTA3LTEwVDAwOjAwOjAwLjAwMFoiLCJlbWFpbCI6Imp1bGlhbmFAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkeU5FMTRYY09XRC9kZ3ZsMXREQy5YdWdhaE01THJQdnQvNFVvUFJQeFc0LmptVHNuUjBaaXkiLCJzdGF0ZSI6dHJ1ZSwiZ2x1Y29zZXJhbmdlIjpbODAsMTIwXX0sImlhdCI6MTY2ODE2ODAwNH0.ul1jt0ra1G3Vc_cdRr6b96Mc8IEhDv8YY8M9tcgN0PM

{
    "teste": "teste",
    "amountHc" : 500,
    "carbRatio" : 15,
    "amountGlucose" : 200,
    "correctionFactor" : 10
}


###
GET http://localhost:3000/api/admin/getalldiabetes


###
GET http://localhost:3000/api/admin/getallusers
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzODExYjYzZjRmMzljMGM0NzY3ODk4OSIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbiIsImJpcnRoZGF5IjoiMTk5Ny0wMS0xNFQwMDowMDowMC4wMDBaIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDF4R056aXk3RGpmaFFJeVNLaG9uSS53bEdXT2RZZ09oNGljbi5xSm5mQ2ptRTFxNFMxZllDIiwic3RhdGUiOnRydWUsImdsdWNvc2VyYW5nZSI6WzgwLDEyMF19LCJpYXQiOjE2Njk0MDY0MTB9.1oNJg2k3Npiq58xzz_ROCNIuZZUxpl_sWxFawAwkk8w

###
POST http://localhost:3000/api/user/updateprofile
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzN2E4NWIyYjNhNGYwZDg1YTE3MjFmOSIsInJvbGUiOiJ1c2VyIiwibmFtZSI6InVzZXIiLCJiaXJ0aGRheSI6IjIwMDAtMDEtMDFUMDA6MDA6MDAuMDAwWiIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJE1pL1FCWHlHNHl2YW1JRTJwWDJiY3U0ZjdETDh5d2ZMY0U3V2xnOVIzTGVDTlBZU2xNMjBPIiwic3RhdGUiOnRydWUsImdsdWNvc2VyYW5nZSI6WzgwLDEyMF19LCJpYXQiOjE2Njg5NzQwODR9.6MRWCIVpQ9Gz2drS87jTuSdrmOJkDho10Pl9YZSyojU

{
    "userEmail": "user@example.com",
    "body": {
        "height": 175,
        "sensitivity": 20,
        "weight": 65,
        "idDiabetes": "638025f7e9a99b2cd2859b31"
    }
}